# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cyildiri <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/07/31 18:59:41 by cyildiri          #+#    #+#              #
#    Updated: 2016/07/31 19:07:32 by cyildiri         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = rush-2
SRC = 
OFILES = 
INCLUDES = 

all: $(NAME)
	
$(NAME):
	gcc -Wall -Wextra -Werror $(SRC) $(INCLUDES)

clean:
	rm -r 

fclean:
	clean
	rm -r $(NAME)

rc: fclean all
